DELETE http://localhost:3001/api/persons/625130f258191d536013b5d0

###

POST http://localhost:3001/api/persons/
Content-Type: application/json 

{
    "name": "Test Person 4", 
    "number": "123"
}

###

GET http://localhost:3001/api/persons/6247dfb01916b66cc36d6ad5

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons/
Content-Type: application/json 

{
    "name": "Te", 
    "number": "123"
}

###

POST https://calm-refuge-58064.herokuapp.com/api/persons/
Content-Type: application/json 

{
    "name": "Test Person", 
    "number": "123"
}

###
DELETE https://calm-refuge-58064.herokuapp.com/api/persons/3194